"""
etf_universe.py
=============================================================================
Universo curato di ETF UCITS reali (dati anagrafici di riferimento) utilizzati
dall'applicazione come "lista bianca" selezionabile.

NOTA SULLA QUALITÀ DEI DATI
---------------------------
- I campi anagrafici (ISIN, ticker, nome, TER, dimensione fondo, tipo
  accumulo/distribuzione, classe di attivo, esposizione geografica e
  settoriale) sono *parametri di riferimento* inseriti a mano e da
  aggiornare periodicamente.
- I prezzi storici e i rendimenti reali vengono recuperati a runtime da
  Yahoo Finance (vedi data_fetcher.py). Se il download fallisce, il sistema
  genera una serie storica *sintetica* (corretta per classe di attivo) così
  l'applicazione resta sempre dimostrabile offline.

Le esposizioni geografiche/settoriali sono approssimazioni basate sui
prospetti ufficiali degli indici sottostanti (MSCI / FTSE / Bloomberg) e
servono a produrre le dashboard di allocazione.
"""

from __future__ import annotations

# Suddivisione settoriale "Broad Market" di riferimento (stile GICS),
# approssimata per gli ETF azionari globali/paese.
BROAD_SECTORS = {
    "Tecnologia": 0.22,
    "Salute": 0.12,
    "Finanziari": 0.13,
    "Consumi Discrezionali": 0.11,
    "Comunicazioni": 0.08,
    "Industria": 0.10,
    "Staples (Beni di Base)": 0.06,
    "Energia": 0.05,
    "Utilities": 0.03,
    "Materiali": 0.03,
    "Real Estate": 0.04,
    "Altro": 0.03,
}

# Universo ETF UCITS (tutti conformi UCITS, regolamento europeo).
#   isin            : codice ISIN ufficiale
#   ticker          : ticker usato internamente (yfinance)
#   yf_ticker       : ticker Yahoo Finance per il download dei prezzi
#   name            : nome completo del fondo
#   asset_class     : 'Equity' | 'Bond'
#   region          : esposizione geografica (dict, somma ~1.0)
#   sectors         : esposizione settoriale (dict, somma ~1.0)
#   ter             : Total Expense Ratio annuo (in %)
#   fund_size_m     : dimensione del fondo in milioni di EUR (applicare filtro >=100)
#   accumulation    : True = a accumulo, False = a distribuzione
#   exp_return      : rendimento atteso ANNUO (solo fallback sintetico)
#   vol             : volatilità ANNUA (solo fallback sintetico)
ETF_UNIVERSE = [
    # ---------------- AZIONARI (Equity) ----------------
    {
        "isin": "IE00BK5BQT80",
        "ticker": "VWCE",
        "yf_ticker": "VWCE.DE",
        "name": "Vanguard FTSE All-World UCITS ETF",
        "asset_class": "Equity",
        "region": {
            "USA": 0.60, "Europa": 0.12, "Pacifico Sviluppato": 0.10,
            "Emergenti": 0.12, "Altri Sviluppati": 0.06,
        },
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.22, "fund_size_m": 14000, "accumulation": True,
        "exp_return": 0.085, "vol": 0.15,
    },
    {
        "isin": "IE00B4L5Y983",
        "ticker": "SWDA",
        "yf_ticker": "SWDA.MI",
        "name": "iShares Core MSCI World UCITS ETF",
        "asset_class": "Equity",
        "region": {
            "USA": 0.70, "Europa": 0.15, "Pacifico Sviluppato": 0.10,
            "Altri Sviluppati": 0.05,
        },
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.20, "fund_size_m": 85000, "accumulation": True,
        "exp_return": 0.085, "vol": 0.15,
    },
    {
        "isin": "IE00B5BMR087",
        "ticker": "CSPX",
        "yf_ticker": "CSPX.L",
        "name": "iShares Core S&P 500 UCITS ETF",
        "asset_class": "Equity",
        "region": {"USA": 1.00},
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.07, "fund_size_m": 95000, "accumulation": True,
        "exp_return": 0.090, "vol": 0.16,
    },
    {
        "isin": "IE00B52XQP83",
        "ticker": "IEMA",
        "yf_ticker": "IEMA.MI",
        "name": "iShares Core MSCI Europe UCITS ETF",
        "asset_class": "Equity",
        "region": {"Europa": 1.00},
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.12, "fund_size_m": 9000, "accumulation": True,
        "exp_return": 0.070, "vol": 0.17,
    },
    {
        "isin": "IE00B4L5YX21",
        "ticker": "SJPA",
        "yf_ticker": "SJPA.MI",
        "name": "iShares Core MSCI Japan UCITS ETF",
        "asset_class": "Equity",
        "region": {"Giappone (Pacifico)": 1.00},
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.12, "fund_size_m": 3500, "accumulation": True,
        "exp_return": 0.070, "vol": 0.16,
    },
    {
        "isin": "IE00BKM4GZ66",
        "ticker": "EIMI",
        "yf_ticker": "EIMI.MI",
        "name": "iShares Core MSCI EM IMI UCITS ETF",
        "asset_class": "Equity",
        "region": {"Emergenti": 1.00},
        "sectors": dict(BROAD_SECTORS),
        "ter": 0.18, "fund_size_m": 5500, "accumulation": True,
        "exp_return": 0.085, "vol": 0.20,
    },
    # ---------------- OBBLIGAZIONARI (Bond) ----------------
    {
        "isin": "IE00BDBRDM35",
        "ticker": "AGGH",
        "yf_ticker": "AGGH.MI",
        "name": "iShares Core Global Aggregate Bond UCITS ETF",
        "asset_class": "Bond",
        "region": {"Obbligazionario Globale (hedged EUR)": 1.00},
        "sectors": {"Obbligazioni": 1.00},
        "ter": 0.10, "fund_size_m": 11000, "accumulation": True,
        "exp_return": 0.025, "vol": 0.05,
    },
    {
        "isin": "IE00B4WXJD03",
        "ticker": "IEGA",
        "yf_ticker": "IEGA.MI",
        "name": "iShares Core Euro Govt Bond UCITS ETF",
        "asset_class": "Bond",
        "region": {"Obbligazionario Eurozona": 1.00},
        "sectors": {"Obbligazioni": 1.00},
        "ter": 0.09, "fund_size_m": 7000, "accumulation": True,
        "exp_return": 0.020, "vol": 0.04,
    },
    {
        "isin": "IE00B3F81R35",
        "ticker": "IEAC",
        "yf_ticker": "IEAC.MI",
        "name": "iShares Euro Corp Bond UCITS ETF",
        "asset_class": "Bond",
        "region": {"Obbligazionario Eurozona (Corp)": 1.00},
        "sectors": {"Obbligazioni": 1.00},
        "ter": 0.09, "fund_size_m": 8000, "accumulation": True,
        "exp_return": 0.030, "vol": 0.05,
    },
    {
        "isin": "IE00B7GZW936",
        "ticker": "IBGM",
        "yf_ticker": "IBGM.MI",
        "name": "iShares Global Corp Bond UCITS ETF",
        "asset_class": "Bond",
        "region": {"Obbligazionario Globale Corp (hedged EUR)": 1.00},
        "sectors": {"Obbligazioni": 1.00},
        "ter": 0.15, "fund_size_m": 4000, "accumulation": True,
        "exp_return": 0.035, "vol": 0.06,
    },
]

# Categoria di default per gli ETF gia' presenti
_DEFAULT_CAT = {
    "VWCE": "Azionario Broad", "SWDA": "Azionario Broad",
    "CSPX": "Azionario Broad", "IEMA": "Azionario Broad",
    "SJPA": "Azionario Broad", "EIMI": "Azionario Broad",
    "AGGH": "Obbligazionario", "IEGA": "Obbligazionario",
    "IEAC": "Obbligazionario", "IBGM": "Obbligazionario",
}
for _e in ETF_UNIVERSE:
    _e.setdefault("category", _DEFAULT_CAT.get(_e["ticker"], "Altro"))

# ---------------------------------------------------------------------------
# Estensione: ETF SETTORIALI, REAL ESTATE e MATERIE PRIME (tutti UCITS)
# I ticker XETRA (XDxx.DE) sono i settoriali S&P 500 di iShares (Acc, USD).
# Metadati (ISIN/TER/dimensione) di riferimento; prezzi reali da Yahoo Finance
# con fallback sintetico.
# ---------------------------------------------------------------------------
NEW_ETFS = [
    {"isin": "IE00B3WTLP36", "ticker": "XDWT", "yf_ticker": "XDWT.DE",
     "name": "iShares S&P 500 Info Technology Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Tecnologia": 1.0},
     "ter": 0.15, "fund_size_m": 20000, "accumulation": True,
     "exp_return": 0.16, "vol": 0.22},
    {"isin": "IE00B3WTLR50", "ticker": "XDWP", "yf_ticker": "XDWP.DE",
     "name": "iShares S&P 500 Health Care Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Salute": 1.0},
     "ter": 0.15, "fund_size_m": 8000, "accumulation": True,
     "exp_return": 0.10, "vol": 0.16},
    {"isin": "IE00B3WTLN28", "ticker": "XDWF", "yf_ticker": "XDWF.DE",
     "name": "iShares S&P 500 Financials Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Finanziari": 1.0},
     "ter": 0.15, "fund_size_m": 5000, "accumulation": True,
     "exp_return": 0.10, "vol": 0.18},
    {"isin": "IE00B3WTLJ19", "ticker": "XDWC", "yf_ticker": "XDWC.DE",
     "name": "iShares S&P 500 Consumer Discretionary Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Consumi Discrezionali": 1.0},
     "ter": 0.15, "fund_size_m": 4000, "accumulation": True,
     "exp_return": 0.12, "vol": 0.20},
    {"isin": "IE00B3WTLH94", "ticker": "XDWE", "yf_ticker": "XDWE.DE",
     "name": "iShares S&P 500 Energy Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Energia": 1.0},
     "ter": 0.15, "fund_size_m": 3000, "accumulation": True,
     "exp_return": 0.08, "vol": 0.22},
    {"isin": "IE00B3WTLF78", "ticker": "XDWU", "yf_ticker": "XDWU.DE",
     "name": "iShares S&P 500 Utilities Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Utilities": 1.0},
     "ter": 0.15, "fund_size_m": 1500, "accumulation": True,
     "exp_return": 0.07, "vol": 0.14},
    {"isin": "IE00B3WTLM11", "ticker": "XDWS", "yf_ticker": "XDWS.DE",
     "name": "iShares S&P 500 Consumer Staples Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Staples (Beni di Base)": 1.0},
     "ter": 0.15, "fund_size_m": 2500, "accumulation": True,
     "exp_return": 0.08, "vol": 0.13},
    {"isin": "IE00B3WTLK95", "ticker": "XDWI", "yf_ticker": "XDWI.DE",
     "name": "iShares S&P 500 Industrials Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Industria": 1.0},
     "ter": 0.15, "fund_size_m": 3000, "accumulation": True,
     "exp_return": 0.10, "vol": 0.17},
    {"isin": "IE00B3WTLQ43", "ticker": "XDWM", "yf_ticker": "XDWM.DE",
     "name": "iShares S&P 500 Materials Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Materiali": 1.0},
     "ter": 0.15, "fund_size_m": 1500, "accumulation": True,
     "exp_return": 0.09, "vol": 0.19},
    {"isin": "IE00B3WTLG85", "ticker": "XDWO", "yf_ticker": "XDWO.DE",
     "name": "iShares S&P 500 Communication Sector UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0}, "sectors": {"Comunicazioni": 1.0},
     "ter": 0.15, "fund_size_m": 2000, "accumulation": True,
     "exp_return": 0.11, "vol": 0.19},
    {"isin": "IE00B1FZS350", "ticker": "IWDP", "yf_ticker": "IWDP.L",
     "name": "iShares Developed Markets Property Yield UCITS ETF",
     "asset_class": "Equity", "category": "Real Estate",
     "region": {"Sviluppati (Global REIT)": 1.0}, "sectors": {"Real Estate": 1.0},
     "ter": 0.40, "fund_size_m": 1250, "accumulation": False,
     "exp_return": 0.07, "vol": 0.18},
    {"isin": "IE00BDFL4P12", "ticker": "IGCC", "yf_ticker": "IGCC.L",
     "name": "iShares Diversified Commodity Swap UCITS ETF",
     "asset_class": "Alternatives", "category": "Materie Prime",
     "region": {"Globale": 1.0}, "sectors": {"Materie Prime": 1.0},
     "ter": 0.19, "fund_size_m": 2260, "accumulation": True,
     "exp_return": 0.04, "vol": 0.15},
]
ETF_UNIVERSE.extend(NEW_ETFS)

# ---------------------------------------------------------------------------
# Seconda estensione: ampliamento database (broad, factor, Nasdaq, REIT EU,
# bond EM/high-yield/inflazione, oro ETC). Metadati di riferimento; i prezzi
# reali arrivano da Yahoo Finance con fallback sintetico.
# ---------------------------------------------------------------------------
NEW_ETFS_2 = [
    {"isin": "IE0032077012", "ticker": "EQQQ", "yf_ticker": "EQQQ.L",
     "name": "Invesco EQQQ NASDAQ-100 UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 1.0},
     "sectors": {"Tecnologia": 0.5, "Comunicazioni": 0.2,
                 "Consumi Discrezionali": 0.2, "Altro": 0.1},
     "ter": 0.30, "fund_size_m": 9000, "accumulation": False,
     "exp_return": 0.14, "vol": 0.22},
    {"isin": "IE00B4X9L533", "ticker": "QDVE", "yf_ticker": "QDVE.DE",
     "name": "iShares MSCI World Information Technology UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Settoriale",
     "region": {"USA": 0.70, "Giappone": 0.08, "Europa": 0.10,
                "Pacifico Sviluppato": 0.05, "Altri Sviluppati": 0.07},
     "sectors": {"Tecnologia": 0.90, "Altro": 0.10},
     "ter": 0.35, "fund_size_m": 4000, "accumulation": True,
     "exp_return": 0.16, "vol": 0.22},
    {"isin": "IE00BF4RFH31", "ticker": "WSML", "yf_ticker": "WSML.DE",
     "name": "iShares MSCI World Small Cap UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Broad",
     "region": {"USA": 0.60, "Europa": 0.15, "Pacifico Sviluppato": 0.10,
                "Emergenti": 0.10, "Altri Sviluppati": 0.05},
     "sectors": {"Tecnologia": 0.18, "Finanziari": 0.16, "Industria": 0.16,
                 "Salute": 0.12, "Consumi Discrezionali": 0.11,
                 "Staples (Beni di Base)": 0.06, "Energia": 0.05,
                 "Utilities": 0.04, "Materiali": 0.06, "Comunicazioni": 0.03,
                 "Altro": 0.03},
     "ter": 0.35, "fund_size_m": 3500, "accumulation": True,
     "exp_return": 0.09, "vol": 0.18},
    {"isin": "IE00B4K48X80", "ticker": "SXR8", "yf_ticker": "SXR8.DE",
     "name": "iShares Core MSCI Europe UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Broad",
     "region": {"Europa": 1.0},
     "sectors": {"Finanziari": 0.18, "Industria": 0.17, "Salute": 0.13,
                 "Consumi Discrezionali": 0.12, "Staples (Beni di Base)": 0.11,
                 "Materiali": 0.09, "Energia": 0.06, "Utilities": 0.06,
                 "Tecnologia": 0.05, "Comunicazioni": 0.02, "Altro": 0.01},
     "ter": 0.12, "fund_size_m": 9000, "accumulation": True,
     "exp_return": 0.08, "vol": 0.16},
    {"isin": "IE00B8XB8Z04", "ticker": "IWQU", "yf_ticker": "IWQU.L",
     "name": "iShares Edge MSCI World Quality Factor UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Broad",
     "region": {"USA": 0.66, "Europa": 0.16, "Pacifico Sviluppato": 0.09,
                "Emergenti": 0.06, "Altri Sviluppati": 0.03},
     "sectors": {"Tecnologia": 0.18, "Finanziari": 0.17, "Salute": 0.14,
                 "Staples (Beni di Base)": 0.11, "Industria": 0.12,
                 "Consumi Discrezionali": 0.11, "Materiali": 0.06,
                 "Energia": 0.04, "Utilities": 0.04, "Comunicazioni": 0.02,
                 "Altro": 0.01},
     "ter": 0.30, "fund_size_m": 1500, "accumulation": True,
     "exp_return": 0.09, "vol": 0.15},
    {"isin": "IE00B8MXLX20", "ticker": "MVOL", "yf_ticker": "MVOL.L",
     "name": "iShares Edge MSCI World Min Volatility UCITS ETF",
     "asset_class": "Equity", "category": "Azionario Broad",
     "region": {"USA": 0.62, "Europa": 0.17, "Pacifico Sviluppato": 0.10,
                "Emergenti": 0.07, "Altri Sviluppati": 0.04},
     "sectors": {"Finanziari": 0.17, "Staples (Beni di Base)": 0.16,
                 "Salute": 0.14, "Industria": 0.13, "Utilities": 0.10,
                 "Tecnologia": 0.09, "Consumi Discrezionali": 0.08,
                 "Materiali": 0.05, "Energia": 0.04, "Comunicazioni": 0.02,
                 "Altro": 0.02},
     "ter": 0.20, "fund_size_m": 1500, "accumulation": True,
     "exp_return": 0.07, "vol": 0.11},
    {"isin": "IE00B9M7QX62", "ticker": "EMBP", "yf_ticker": "EMBP.L",
     "name": "iShares J.P. Morgan EM Bond UCITS ETF",
     "asset_class": "Bond", "category": "Obbligazionario",
     "region": {"Emergenti": 1.0}, "sectors": {"Obbligazioni": 1.0},
     "ter": 0.50, "fund_size_m": 1500, "accumulation": False,
     "exp_return": 0.05, "vol": 0.07},
    {"isin": "IE00B66FQX63", "ticker": "IHYG", "yf_ticker": "IHYG.L",
     "name": "iShares Euro High Yield Corp Bond UCITS ETF",
     "asset_class": "Bond", "category": "Obbligazionario",
     "region": {"Europa": 1.0}, "sectors": {"Obbligazioni": 1.0},
     "ter": 0.50, "fund_size_m": 2500, "accumulation": False,
     "exp_return": 0.04, "vol": 0.06},
    {"isin": "IE00B3FH32M1", "ticker": "TIKL", "yf_ticker": "TIKL.L",
     "name": "iShares Global Inflation Linked Govt Bond UCITS ETF",
     "asset_class": "Bond", "category": "Obbligazionario",
     "region": {"Globale": 1.0}, "sectors": {"Obbligazioni": 1.0},
     "ter": 0.20, "fund_size_m": 800, "accumulation": True,
     "exp_return": 0.025, "vol": 0.05},
    {"isin": "IE00B1FZR446", "ticker": "IPRP", "yf_ticker": "IPRP.L",
     "name": "iShares European Property Yield UCITS ETF",
     "asset_class": "Equity", "category": "Real Estate",
     "region": {"Europa": 1.0}, "sectors": {"Real Estate": 1.0},
     "ter": 0.40, "fund_size_m": 700, "accumulation": False,
     "exp_return": 0.06, "vol": 0.18},
    {"isin": "IE00B4ND3602", "ticker": "SGLN", "yf_ticker": "SGLN.L",
     "name": "iShares Physical Gold ETC",
     "asset_class": "Alternatives", "category": "Materie Prime",
     "region": {"Globale": 1.0}, "sectors": {"Materie Prime": 1.0},
     "ter": 0.12, "fund_size_m": 15000, "accumulation": True,
     "exp_return": 0.04, "vol": 0.15},
    {"isin": "DE000A0S9GB0", "ticker": "4GLD", "yf_ticker": "4GLD.DE",
     "name": "Xetra-Gold ETC",
     "asset_class": "Alternatives", "category": "Materie Prime",
     "region": {"Globale": 1.0}, "sectors": {"Materie Prime": 1.0},
     "ter": 0.00, "fund_size_m": 12000, "accumulation": True,
     "exp_return": 0.04, "vol": 0.15},
]
ETF_UNIVERSE.extend(NEW_ETFS_2)

# ---------------------------------------------------------------------------
# Terza estensione: ampliamento massimo del database. Metadati curati arricchiti
# con dati reali (regione/settori/nome/dimensione) da JustETF via fetch_justetf.
# ---------------------------------------------------------------------------
NEW_ETFS_3 = [   {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.085,
        'fund_size_m': 60000,
        'isin': 'IE00B1XNHC34',
        'name': 'iShares Global Clean Energy Transition UCITS ETF USD (Dist)',
        'region': {   'Altri Sviluppati': 0.25329999999999997,
                      'Cina': 0.1815,
                      'Emergenti': 0.054900000000000004,
                      'India': 0.060700000000000004,
                      'USA': 0.4496},
        'sectors': {   'Altro': 0.3535999999999999,
                       'Industria': 0.5670000000000001,
                       'Tecnologia': 0.0794},
        'ter': 0.2,
        'ticker': 'IWDA',
        'vol': 0.15,
        'yf_ticker': 'IWDA.AS'},
    {   'accumulation': False,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.09,
        'fund_size_m': 90000,
        'isin': 'IE00B3XXRP09',
        'name': 'Vanguard S&P 500 UCITS ETF (USD) Distributing',
        'region': {'Altri Sviluppati': 0.0179, 'Europa': 0.011200000000000002, 'USA': 0.9709},
        'sectors': {   'Altro': 0.3259,
                       'Finanziari': 0.12960000000000002,
                       'Staples (Beni di Base)': 0.0876,
                       'Tecnologia': 0.4569},
        'ter': 0.07,
        'ticker': 'VUSA',
        'vol': 0.16,
        'yf_ticker': 'VUSA.L'},
    {   'accumulation': False,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.085,
        'fund_size_m': 30000,
        'isin': 'IE00B3RBWM25',
        'name': 'Vanguard FTSE All-World UCITS ETF (USD) Distributing',
        'region': {   'Altri Sviluppati': 0.2788,
                      'Emergenti': 0.0337,
                      'Giappone': 0.0588,
                      'Regno Unito': 0.032,
                      'USA': 0.5967},
        'sectors': {   'Altro': 0.2738,
                       'Finanziari': 0.1775,
                       'Industria': 0.0951,
                       'Staples (Beni di Base)': 0.08039999999999999,
                       'Tecnologia': 0.3732},
        'ter': 0.22,
        'ticker': 'VWRL',
        'vol': 0.15,
        'yf_ticker': 'VWRL.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.08,
        'fund_size_m': 9000,
        'isin': 'IE00B4L5GL87',
        'name': 'iShares Core EURO STOXX 50 UCITS ETF',
        'region': {'Europa': 1.0},
        'sectors': {   'Altro': 0.01,
                       'Comunicazioni': 0.02,
                       'Consumi Discrezionali': 0.12,
                       'Energia': 0.06,
                       'Finanziari': 0.18,
                       'Industria': 0.17,
                       'Materiali': 0.09,
                       'Salute': 0.13,
                       'Staples (Beni di Base)': 0.11,
                       'Tecnologia': 0.05,
                       'Utilities': 0.06},
        'ter': 0.12,
        'ticker': 'SX5E',
        'vol': 0.17,
        'yf_ticker': 'SX5E.DE'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.08,
        'fund_size_m': 30000,
        'isin': 'DE000A0H08A3',
        'name': 'iShares Core DAX UCITS ETF',
        'region': {'Europa': 1.0},
        'sectors': {   'Altro': 0.02,
                       'Consumi Discrezionali': 0.1,
                       'Energia': 0.07,
                       'Finanziari': 0.17,
                       'Industria': 0.2,
                       'Materiali': 0.13,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.11,
                       'Tecnologia': 0.04,
                       'Utilities': 0.04},
        'ter': 0.16,
        'ticker': 'EXS1',
        'vol': 0.18,
        'yf_ticker': 'EXS1.DE'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.07,
        'fund_size_m': 15000,
        'isin': 'IE00B1FZS867',
        'name': 'iShares Core FTSE 100 UCITS ETF',
        'region': {'Europa': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Consumi Discrezionali': 0.1,
                       'Energia': 0.14,
                       'Finanziari': 0.22,
                       'Industria': 0.09,
                       'Materiali': 0.11,
                       'Salute': 0.11,
                       'Staples (Beni di Base)': 0.11,
                       'Tecnologia': 0.03,
                       'Utilities': 0.06},
        'ter': 0.07,
        'ticker': 'ISF',
        'vol': 0.16,
        'yf_ticker': 'ISF.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.08,
        'fund_size_m': 5000,
        'isin': 'CH0019657329',
        'name': 'iShares SMI UCITS ETF',
        'region': {'Altri Sviluppati': 1.0},
        'sectors': {   'Altro': 0.02,
                       'Consumi Discrezionali': 0.08,
                       'Finanziari': 0.12,
                       'Industria': 0.03,
                       'Materiali': 0.2,
                       'Salute': 0.4,
                       'Staples (Beni di Base)': 0.15},
        'ter': 0.2,
        'ticker': 'CSSMI',
        'vol': 0.16,
        'yf_ticker': 'CSSMI.SW'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.07,
        'fund_size_m': 2000,
        'isin': 'IE00B3F81493',
        'name': 'iShares MSCI Pacific ex Japan UCITS ETF',
        'region': {'Pacifico Sviluppato': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.15,
        'ticker': 'IAPX',
        'vol': 0.16,
        'yf_ticker': 'IAPX.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.09,
        'fund_size_m': 6000,
        'isin': 'IE00B42MKD19',
        'name': 'iShares MSCI EM Asia UCITS ETF',
        'region': {'Emergenti': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.2,
        'ticker': 'EEMA',
        'vol': 0.2,
        'yf_ticker': 'EEMA.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.1,
        'fund_size_m': 4000,
        'isin': 'IE00BZCQB185',
        'name': 'iShares MSCI India UCITS ETF USD (Acc)',
        'region': {'Altri Sviluppati': 0.0046, 'India': 0.9954000000000001},
        'sectors': {   'Altro': 0.4726,
                       'Consumi Discrezionali': 0.0915,
                       'Finanziari': 0.319,
                       'Industria': 0.11689999999999999},
        'ter': 0.65,
        'ticker': 'IIND',
        'vol': 0.22,
        'yf_ticker': 'IIND.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.14,
        'fund_size_m': 9000,
        'isin': 'IE00B3WMW970',
        'name': 'iShares NASDAQ 100 UCITS ETF (Acc)',
        'region': {'USA': 1.0},
        'sectors': {   'Altro': 0.1,
                       'Comunicazioni': 0.2,
                       'Consumi Discrezionali': 0.2,
                       'Tecnologia': 0.5},
        'ter': 0.33,
        'ticker': 'CNDX',
        'vol': 0.22,
        'yf_ticker': 'CNDX.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.08,
        'fund_size_m': 800,
        'isin': 'IE00B6R52253',
        'name': 'iShares MSCI Canada UCITS ETF',
        'region': {'Altri Sviluppati': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.2,
        'ticker': 'ICAN',
        'vol': 0.17,
        'yf_ticker': 'ICAN.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.09,
        'fund_size_m': 1000,
        'isin': 'IE00B4N99D64',
        'name': 'iShares MSCI South Korea UCITS ETF',
        'region': {'Emergenti': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.19,
        'ticker': 'IKRW',
        'vol': 0.22,
        'yf_ticker': 'IKRW.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.1,
        'fund_size_m': 1000,
        'isin': 'IE00B4N99F79',
        'name': 'iShares MSCI Taiwan UCITS ETF',
        'region': {'Emergenti': 1.0},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.19,
        'ticker': 'ITWN',
        'vol': 0.22,
        'yf_ticker': 'ITWN.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.085,
        'fund_size_m': 3000,
        'isin': 'IE00B8GKDB10',
        'name': 'Vanguard FTSE All-World High Dividend Yield UCITS ETF Distributing',
        'region': {   'Altri Sviluppati': 0.4213,
                      'Giappone': 0.092,
                      'Regno Unito': 0.0641,
                      'Svizzera': 0.047,
                      'USA': 0.37560000000000004},
        'sectors': {   'Altro': 0.5186,
                       'Finanziari': 0.2929,
                       'Industria': 0.09630000000000001,
                       'Staples (Beni di Base)': 0.0922},
        'ter': 0.3,
        'ticker': 'IWVL',
        'vol': 0.15,
        'yf_ticker': 'IWVL.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.09,
        'fund_size_m': 3000,
        'isin': 'IE00BP3QZ825',
        'name': 'iShares Edge MSCI World Momentum Factor UCITS ETF (Acc)',
        'region': {   'Altri Sviluppati': 0.1968,
                      'Giappone': 0.1106,
                      'Regno Unito': 0.042800000000000005,
                      'USA': 0.6498},
        'sectors': {   'Altro': 0.2161,
                       'Energia': 0.0906,
                       'Finanziari': 0.1326,
                       'Industria': 0.1364,
                       'Tecnologia': 0.4243},
        'ter': 0.3,
        'ticker': 'IWMO',
        'vol': 0.16,
        'yf_ticker': 'IWMO.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.088,
        'fund_size_m': 1500,
        'isin': 'IE00BJL5DX23',
        'name': 'iShares Edge MSCI World Multifactor UCITS ETF',
        'region': {   'Altri Sviluppati': 0.03,
                      'Emergenti': 0.06,
                      'Europa': 0.16,
                      'Pacifico Sviluppato': 0.09,
                      'USA': 0.66},
        'sectors': {   'Altro': 0.03,
                       'Comunicazioni': 0.08,
                       'Consumi Discrezionali': 0.11,
                       'Energia': 0.05,
                       'Finanziari': 0.13,
                       'Industria': 0.1,
                       'Materiali': 0.03,
                       'Real Estate': 0.04,
                       'Salute': 0.12,
                       'Staples (Beni di Base)': 0.06,
                       'Tecnologia': 0.22,
                       'Utilities': 0.03},
        'ter': 0.3,
        'ticker': 'WINC',
        'vol': 0.15,
        'yf_ticker': 'WINC.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Broad',
        'exp_return': 0.085,
        'fund_size_m': 4000,
        'isin': 'IE00BK5BC891',
        'name': 'L&G Clean Water UCITS ETF',
        'region': {   'Altri Sviluppati': 0.1117,
                      'Giappone': 0.14279999999999998,
                      'Regno Unito': 0.10859999999999999,
                      'Svizzera': 0.061900000000000004,
                      'USA': 0.575},
        'sectors': {'Altro': 0.446, 'Industria': 0.5539999999999999},
        'ter': 0.24,
        'ticker': 'V3AA',
        'vol': 0.15,
        'yf_ticker': 'V3AA.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.09,
        'fund_size_m': 5000,
        'isin': 'IE00B1XNLRN9',
        'name': 'iShares Global Clean Energy UCITS ETF',
        'region': {'Altri Sviluppati': 0.1, 'Emergenti': 0.2, 'Europa': 0.3, 'USA': 0.4},
        'sectors': {'Energia': 0.7, 'Materiali': 0.3},
        'ter': 0.65,
        'ticker': 'INRG',
        'vol': 0.25,
        'yf_ticker': 'INRG.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.1,
        'fund_size_m': 2000,
        'isin': 'IE00BM0WH173',
        'name': 'iShares Automation & Robotics UCITS ETF',
        'region': {'Europa': 0.35, 'Giappone': 0.15, 'USA': 0.5},
        'sectors': {'Industria': 0.7, 'Tecnologia': 0.3},
        'ter': 0.4,
        'ticker': 'RBOT',
        'vol': 0.22,
        'yf_ticker': 'RBOT.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.11,
        'fund_size_m': 1500,
        'isin': 'IE00BYZK4552',
        'name': 'iShares Automation & Robotics UCITS ETF',
        'region': {   'Altri Sviluppati': 0.1628,
                      'Europa': 0.0642,
                      'Giappone': 0.1402,
                      'Svizzera': 0.054400000000000004,
                      'USA': 0.5784},
        'sectors': {   'Altro': 0.029299999999999996,
                       'Consumi Discrezionali': 0.0042,
                       'Industria': 0.3102,
                       'Tecnologia': 0.6563},
        'ter': 0.4,
        'ticker': 'ISPY',
        'vol': 0.22,
        'yf_ticker': 'ISPY.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.14,
        'fund_size_m': 2000,
        'isin': 'IE00BML0TBX8',
        'name': 'iShares MSCI World Semiconductors UCITS ETF',
        'region': {'Emergenti': 0.2, 'Europa': 0.1, 'USA': 0.7},
        'sectors': {'Tecnologia': 1.0},
        'ter': 0.35,
        'ticker': 'SEMI',
        'vol': 0.26,
        'yf_ticker': 'SEMI.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.06,
        'fund_size_m': 1500,
        'isin': 'IE00B8KD8X36',
        'name': 'iShares MSCI World Gold Miners UCITS ETF',
        'region': {   'Altri Sviluppati': 0.2,
                      'Emergenti': 0.1,
                      'Europa': 0.1,
                      'Pacifico Sviluppato': 0.1,
                      'USA': 0.5},
        'sectors': {'Materiali': 1.0},
        'ter': 0.55,
        'ticker': 'GIGM',
        'vol': 0.28,
        'yf_ticker': 'GIGM.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.1,
        'fund_size_m': 1500,
        'isin': 'IE00BYX5NC33',
        'name': 'iShares MSCI World Aerospace & Defense UCITS ETF',
        'region': {'Europa': 0.35, 'Pacifico Sviluppato': 0.05, 'USA': 0.6},
        'sectors': {'Industria': 1.0},
        'ter': 0.4,
        'ticker': 'IADE',
        'vol': 0.2,
        'yf_ticker': 'IADE.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.08,
        'fund_size_m': 1500,
        'isin': 'IE00B1FZS913',
        'name': 'iShares Euro Government Bond 15-30yr UCITS ETF (Dist)',
        'region': {'Altri Sviluppati': 0.1572, 'Europa': 0.8428},
        'sectors': {'Altro': 0.9842, 'Finanziari': 0.0166},
        'ter': 0.65,
        'ticker': 'IH2O',
        'vol': 0.2,
        'yf_ticker': 'IH2O.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.13,
        'fund_size_m': 1000,
        'isin': 'IE00B5WMR770',
        'name': 'iShares MSCI World Cloud Computing UCITS ETF',
        'region': {'Europa': 0.2, 'USA': 0.8},
        'sectors': {'Tecnologia': 1.0},
        'ter': 0.4,
        'ticker': 'WCLD',
        'vol': 0.24,
        'yf_ticker': 'WCLD.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.1,
        'fund_size_m': 2000,
        'isin': 'IE00B53SZB19',
        'name': 'iShares Nasdaq 100 UCITS ETF (Acc)',
        'region': {   'Altri Sviluppati': 0.036199999999999996,
                      'Regno Unito': 0.018799999999999997,
                      'USA': 0.945},
        'sectors': {   'Altro': 0.1482,
                       'Consumi Discrezionali': 0.0374,
                       'Staples (Beni di Base)': 0.11130000000000001,
                       'Tecnologia': 0.7031000000000001},
        'ter': 0.35,
        'ticker': 'IWHO',
        'vol': 0.16,
        'yf_ticker': 'IWHO.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.09,
        'fund_size_m': 2000,
        'isin': 'IE00B53SXM35',
        'name': 'iShares MSCI World Financials Sector UCITS ETF',
        'region': {'Emergenti': 0.05, 'Europa': 0.35, 'Pacifico Sviluppato': 0.1, 'USA': 0.5},
        'sectors': {'Finanziari': 1.0},
        'ter': 0.35,
        'ticker': 'IWFN',
        'vol': 0.18,
        'yf_ticker': 'IWFN.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.11,
        'fund_size_m': 3000,
        'isin': 'IE00B3WMW974',
        'name': 'iShares NASDAQ Biotech UCITS ETF',
        'region': {'USA': 1.0},
        'sectors': {'Salute': 1.0},
        'ter': 0.35,
        'ticker': 'IBIO',
        'vol': 0.22,
        'yf_ticker': 'IBIO.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Azionario Settoriale',
        'exp_return': 0.08,
        'fund_size_m': 3000,
        'isin': 'IE00B7RCXR36',
        'name': 'iShares STOXX Europe 600 Banks UCITS ETF',
        'region': {'Europa': 1.0},
        'sectors': {'Finanziari': 1.0},
        'ter': 0.15,
        'ticker': 'BNKE',
        'vol': 0.22,
        'yf_ticker': 'BNKE.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.03,
        'fund_size_m': 3000,
        'isin': 'IE00B3VWN985',
        'name': 'iShares $ Treasury Bond 7-10yr UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.1,
        'ticker': 'IBTM',
        'vol': 0.06,
        'yf_ticker': 'IBTM.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.02,
        'fund_size_m': 3000,
        'isin': 'IE00B14X4Q57',
        'name': 'iShares Euro Government Bond 1-3yr UCITS ETF (Dist)',
        'region': {'Altri Sviluppati': 0.512, 'Europa': 0.48799999999999993},
        'sectors': {'Altro': 1.001},
        'ter': 0.1,
        'ticker': 'IEGM',
        'vol': 0.05,
        'yf_ticker': 'IEGM.L'},
    {   'accumulation': False,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.05,
        'fund_size_m': 5000,
        'isin': 'IE00B4L6FZ25',
        'name': 'iShares $ High Yield Corp Bond UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.5,
        'ticker': 'IHYU',
        'vol': 0.08,
        'yf_ticker': 'IHYU.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.025,
        'fund_size_m': 2000,
        'isin': 'IE00B45M2323',
        'name': 'iShares US Inflation Linked Bond UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.15,
        'ticker': 'IUSI',
        'vol': 0.05,
        'yf_ticker': 'IUSI.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.015,
        'fund_size_m': 3000,
        'isin': 'IE00B1FZS820',
        'name': 'iShares EUR Ultra Short Bond UCITS ETF',
        'region': {'Obbligazionario Eurozona': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.12,
        'ticker': 'ERNE',
        'vol': 0.02,
        'yf_ticker': 'ERNE.L'},
    {   'accumulation': False,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.05,
        'fund_size_m': 2000,
        'isin': 'IE00B6T5SX26',
        'name': 'iShares J.P. Morgan EM Local Govt Bond UCITS ETF',
        'region': {'Emergenti': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.5,
        'ticker': 'IEML',
        'vol': 0.07,
        'yf_ticker': 'IEML.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.02,
        'fund_size_m': 1500,
        'isin': 'IE00B4TYW539',
        'name': 'iShares Global Green Bond UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.2,
        'ticker': 'IGBO',
        'vol': 0.05,
        'yf_ticker': 'IGBO.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.03,
        'fund_size_m': 8000,
        'isin': 'IE00B1FZS798',
        'name': 'iShares USD Treasury Bond 7-10yr UCITS ETF (Dist)',
        'region': {'Altri Sviluppati': 0.401, 'USA': 0.599},
        'sectors': {'Altro': 1.0},
        'ter': 0.1,
        'ticker': 'SLQD',
        'vol': 0.05,
        'yf_ticker': 'SLQD.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.03,
        'fund_size_m': 3000,
        'isin': 'IE00B6X2VY59',
        'name': 'iShares EUR Corporate Bond Interest Rate Hedged ESG SRI UCITS ETF',
        'region': {   'Altri Sviluppati': 0.5586,
                      'Europa': 0.2334,
                      'Regno Unito': 0.065,
                      'USA': 0.14300000000000002},
        'sectors': {   'Altro': 0.48949999999999994,
                       'Finanziari': 0.40880000000000005,
                       'Industria': 0.0583,
                       'Staples (Beni di Base)': 0.0434},
        'ter': 0.15,
        'ticker': 'IBGS',
        'vol': 0.05,
        'yf_ticker': 'IBGS.L'},
    {   'accumulation': True,
        'asset_class': 'Bond',
        'category': 'Obbligazionario',
        'exp_return': 0.025,
        'fund_size_m': 5000,
        'isin': 'IE00BZ043R67',
        'name': 'iShares Global Aggregate Bond UCITS ETF (Acc)',
        'region': {'Globale': 1.0},
        'sectors': {'Obbligazioni': 1.0},
        'ter': 0.1,
        'ticker': 'AGGA',
        'vol': 0.05,
        'yf_ticker': 'AGGA.L'},
    {   'accumulation': False,
        'asset_class': 'Equity',
        'category': 'Real Estate',
        'exp_return': 0.07,
        'fund_size_m': 2000,
        'isin': 'IE00B8GF1M35',
        'name': 'State Street SPDR Dow Jones Global Real Estate UCITS ETF USD Unhedged (Dist)',
        'region': {   'Altri Sviluppati': 0.1361,
                      'Giappone': 0.0691,
                      'Pacifico Sviluppato': 0.0258,
                      'Regno Unito': 0.036699999999999997,
                      'USA': 0.7323000000000001},
        'sectors': {'Altro': 0.0011, 'Finanziari': 0.998, 'Industria': 0.0008},
        'ter': 0.4,
        'ticker': 'IUSP',
        'vol': 0.18,
        'yf_ticker': 'IUSP.L'},
    {   'accumulation': True,
        'asset_class': 'Equity',
        'category': 'Real Estate',
        'exp_return': 0.06,
        'fund_size_m': 800,
        'isin': 'IE00BD9X5BK0',
        'name': 'iShares European Residential UCITS ETF',
        'region': {'Europa': 1.0},
        'sectors': {'Real Estate': 1.0},
        'ter': 0.4,
        'ticker': 'IWRE',
        'vol': 0.17,
        'yf_ticker': 'IWRE.L'},
    {   'accumulation': True,
        'asset_class': 'Alternatives',
        'category': 'Materie Prime',
        'exp_return': 0.04,
        'fund_size_m': 5000,
        'isin': 'IE00B4N3CJ59',
        'name': 'Xtrackers Bloomberg Commodity Swap UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Materie Prime': 1.0},
        'ter': 0.19,
        'ticker': 'XCBO',
        'vol': 0.16,
        'yf_ticker': 'XCBO.DE'},
    {   'accumulation': True,
        'asset_class': 'Alternatives',
        'category': 'Materie Prime',
        'exp_return': 0.04,
        'fund_size_m': 3000,
        'isin': 'IE00B1FZS828',
        'name': 'iShares Physical Silver ETC',
        'region': {'Globale': 1.0},
        'sectors': {'Materie Prime': 1.0},
        'ter': 0.2,
        'ticker': 'ISLV',
        'vol': 0.22,
        'yf_ticker': 'ISLV.L'},
    {   'accumulation': True,
        'asset_class': 'Alternatives',
        'category': 'Materie Prime',
        'exp_return': 0.04,
        'fund_size_m': 1000,
        'isin': 'IE00B1FZS940',
        'name': 'iShares Agriculture UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Materie Prime': 1.0},
        'ter': 0.2,
        'ticker': 'AGRT',
        'vol': 0.2,
        'yf_ticker': 'AGRT.L'},
    {   'accumulation': True,
        'asset_class': 'Alternatives',
        'category': 'Materie Prime',
        'exp_return': 0.04,
        'fund_size_m': 800,
        'isin': 'IE00B1FZS657',
        'name': 'iShares Industrial Metals UCITS ETF',
        'region': {'Globale': 1.0},
        'sectors': {'Materia Prime': 1.0},
        'ter': 0.19,
        'ticker': 'IMET',
        'vol': 0.2,
        'yf_ticker': 'IMET.L'}]
ETF_UNIVERSE.extend(NEW_ETFS_3)

# Indici di comodo
ETF_BY_TICKER = {e["ticker"]: e for e in ETF_UNIVERSE}
ETF_BY_ISIN = {e["isin"]: e for e in ETF_UNIVERSE}
ETF_BY_YF = {e["yf_ticker"]: e for e in ETF_UNIVERSE}


def get_etf(ticker: str) -> dict:
    """Restituisce i metadati di un ETF dal suo ticker interno."""
    return ETF_BY_TICKER.get(ticker)
